# Generated by Django 4.2.29 on 2026-04-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_property_rejection_reason_property_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
